name: Run tests

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env variables
        run: cp .env.template .env
      - name: Build
        run: docker compose --profile application build
      - name: Run
        run: docker compose --profile application up
      - name: Run tests
        run: docker compose exec -T fregepoc-backend pytest
